blank_issues_enabled: true
contact_links:
  - name: Question Only
    url: https://github.com/Batfoxkid/Freak-Fortress-2-Rewrite/discussions/new?category=q-a
    about: If it's only a question and not a bug or feature request.
  - name: VSH / Freak Fortress Forum
    url: https://forums.alliedmods.net/forumdisplay.php?f=154
    about: If it's specific to your server and not related to main plugin.
