name: Compile

on:
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Environments
        run: |
          echo "SM_VERSION=1.11" >> $GITHUB_ENV
      
      - name: Install
        run: |
          bash scripts/install.sh
      
      - name: Compile
        run: |
          cd build/addons/sourcemod/scripting
          ./spcomp -E freak_fortress_2.sp -o ../plugins/freak_fortress_2.smx
          ./spcomp -E ff2r_default_abilities.sp -o ../plugins/ff2r_default_abilities.smx
          ./spcomp -E ff2r_menu_abilities.sp -o ../plugins/ff2r_menu_abilities.smx
